name: rooms-app

services:
  spring-app:
    build: # required if we build the project image
      context: . #project folder relative to DockerFile
      dockerfile: Dockerfile #DockerFile name (this is required if the default name is not respected)
      args: #ARG variables for the build
        APP_VERSION: "1.0.0"
    image: rooms-app-image
    container_name: rooms-app-container
    #defines the policy that the platform applies on container termination.
    restart: on-failure:3 #restart the container if the exit code indicates an error
    networks:
      - rooms-app-network
    ports:
      - "8088:8080"
    env_file:
      - ./env/app.dev.env #env file containing the Spring App environment variables for DEV
    #As an alternative we can use env variables like this too
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://rooms-db-container:5432/rooms-dev-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      database: #This is the another service called "database" required to start current service
        required: true
        condition: service_healthy #or service_started, service_completed_successfully

  database:
    image: postgres:18
    container_name: rooms-db-container
    restart: on-failure:3
    environment: #The environment variables to set in when the container is first started
      POSTGRES_DB: rooms-db #default database
      POSTGRES_USER: root #default superuser username
      POSTGRES_PASSWORD: root #default superuser password
        #-  POSTGRES_PASSWORD=root #another way to set an environment variable (with - and =)
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql #"/var/lib/postgresql" is the container's internal data directory path
    networks:
      - rooms-app-network
    healthcheck:
      #test if the database is ready with username "root" and database "rooms-db"
      test: ["CMD-SHELL", "pg_isready -U root -d rooms-db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    #if "external=true" means this volume is external (not managed by docker-compose) and shouldn't be prefixed by the project name
    #external: true
networks:
  rooms-app-network: