server:
  port: 8080

spring:
  application:
    name: Rooms - Spring MVC Security

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

#  mvc:
#    apiversion:
#      use:
#        #API path segment index
#        path-segment: 1
#      required: false
#      default: 1



